// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4kHBOBgEnsPkIgTHJLg4I6R74nSzHlN0',
    appId: '1:82872525389:android:da695342bbd04f96cbf204',
    messagingSenderId: '82872525389',
    projectId: 'trash---app-867e8',
    storageBucket: 'trash---app-867e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZMgGPrnPfj7VQDpgtNE9585ntpzLUG5o',
    appId: '1:82872525389:ios:bfaa1e9165683754cbf204',
    messagingSenderId: '82872525389',
    projectId: 'trash---app-867e8',
    storageBucket: 'trash---app-867e8.appspot.com',
    iosBundleId: 'com.example.trash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZMgGPrnPfj7VQDpgtNE9585ntpzLUG5o',
    appId: '1:82872525389:ios:9cf2313b42323c7ecbf204',
    messagingSenderId: '82872525389',
    projectId: 'trash---app-867e8',
    storageBucket: 'trash---app-867e8.appspot.com',
    iosBundleId: 'com.example.trash.RunnerTests',
  );
}
